spring:
  application:
    name: haruplay
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.project.user
  security:
    debug: true
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration:
    access-token: 3600 # 1시간
    refresh-token: 604800000 # 7일
